# Generated by Django 4.1.7 on 2023-03-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('time', models.TimeField(default='00:00', verbose_name='время исполнения')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('pleasant_habit', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('frequency', models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность выполнения привычки')),
                ('bonus', models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.TimeField(default='00:03', verbose_name='время на выполнение')),
                ('status', models.CharField(choices=[('public', 'публичная привычка'), ('private', 'приватная привычка')], default='public', max_length=20, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
        ),
    ]
